### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by Reiiters** [xdavidhu/lanGhost#11]
Do you have any plans to add **https** support to 'mitm' and 'replaceimg' functions?

**Comment by xdavidhu** [comment]
Hi!

Unfortunately it's not possible to add HTTPS support to the attacks, because HTTPS connections are encrypted and can't be easily modified. There are techniques out there for downgrading HTTPS connections to HTTP (eg. `sslstrip`) but they don't always work reliably and can be messy so I decided not to use them with lanGhost.
