### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by ChandraOrbit** [xdavidhu/lanGhost#15]
I'm having some constraints:
1. if run / replaceimg then the target can not connect to the internet.
2. If the target using antivirus it will be detected as ARP Poisoning at run / mitm.
3. Network will decrease speed.

that's some of the obstacles I'm having.

**Comment by xdavidhu** [comment]
Hi, maybe the PI is too slow to handle the traffic, or there is some other issues on your network. As I said in the other issue you made, a lot of things could cause instability in case of ARP spoof attacks, and I can't debug it remotely unfortunately.

As for the Antivirus, yes, an antivirus could detect ARP spoofing, and that's how lanGhost works, and its a quite noisy attack method.

For the network speed, it will decrease, because all the traffic is running through the PI in case of an attack.
